version: "3.9"

networks:
  backend:
  external:

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "p@ssword12#"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    ports:
      - "8001:1433"

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebAPI/Dockerfile
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=customerdb
      - DB_NAME=customer
      - DB_SA_PASSWORD=p@ssword12#
    # ports:
    #   - "8002:8080"

  productdb:
    container_name: product-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "p@ssword12#"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    ports:
      - "8003:1433"

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebAPI/Dockerfile
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=productdb
      - DB_NAME=product
      - DB_SA_PASSWORD=p@ssword12#
    # ports:
    #   - 8004:8080
  
  orderdb:
    container_name: order-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "p@ssword12#"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    ports:
      - "8005:1433"

  orderwebapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: OrderWebAPI/Dockerfile
    networks:
      - backend
    # ports:
    #   - 8006:8080 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=orderdb
      - DB_NAME=order
      - DB_SA_PASSWORD=p@ssword12#

  cartdb:
    container_name: cart-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "p@ssword12#"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    ports:
      - "8011:1433"

  cartwebapi:
    container_name: cart-api
    image: ${DOCKER_REGISTRY-}cartwebapi
    build:
      context: .
      dockerfile: CartWebAPI/Dockerfile
    networks:
      - backend
    ports:
      - "8009:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=cartdb
      - DB_NAME=cart
      - DB_SA_PASSWORD=p@ssword12#

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8000:8080
    networks:
      - backend


  authenticationwebapi:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: AuthenticationWebApi/Dockerfile
    networks:
      - backend

  bokunadapterwebapi:
    container_name: bokun-adapter-api
    image: ${DOCKER_REGISTRY-}bokunadapterwebapi
    build:
      context: .
      dockerfile: BokunAdapterWebAPI/Dockerfile
    ports:
      - "8004:8080"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  handycraftsadapterwebapi:
    container_name: handycrafts-adapter-api
    image: ${DOCKER_REGISTRY-}handycraftsadapterwebapi
    build:
      context: .
      dockerfile: HandyCraftsWebAPI/Dockerfile
    ports:
      - "8006:8080"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  adapterdb:
    container_name: adapter-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "p@ssword12#"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    ports:
    - "8015:1433"

  integrationservice:
    container_name: integration-service
    image: ${DOCKER_REGISTRY-}integrationservice
    build:
      context: .
      dockerfile: IntegrationService/Dockerfile
    ports:
      - "8016:8080"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=adapterdb
      - DB_NAME=adapter
      - DB_SA_PASSWORD=p@ssword12#


